config/routes.rb
Rails.application.routes.draw do

  resources :brands
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :carts

  get 'store/index'

  root 'store#index' , as: 'store'
  resources :products

end

app/models/cart.rb
class Cart 
  include Neo4j::ActiveNode
  include CurrentCart

  has_many :out, :products , model_class: :Product, rel_class: :Contain

  property :total_price, type: BigDecimal

  def sum_price
    @total_price = 0
    products(:node, :rel).each_with_rel do |node, rel|
      @total_price += rel[:quantity]*node.price
    end
    @total_price
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  extend Neo4j::Core

  before_action :create_cart, only: [:create]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy, :show]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @p=Product.find(params[:product_id])
    r = @cart.products(:pd,:rel).where('pd.uuid = {pid}',pid: @p.uuid).pluck(:pd,:rel)
    if r.empty?
      @cart.products.create(@p, quantity: 1)
    else
      r.first.last.quantity += 1
      r.first.last.save
    end
    recc
      respond_to do |format|
        if @cart.save
          format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
          format.js   { @current_item = @p }
          format.json { render :show, status: :created, location: @cart }
        else
          format.html { render :new }
          format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to store_path, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2>Your Cart</h2>
<table>
  <% @cart.products(:node, :rel).each_with_rel do |node, rel| %>
      <% if node == @current_item %>
          <tr id = "current_item">
      <% else %>
          <tr>
      <% end %>
        <td><%= rel[:quantity] %>&times;</td>
        <td><%= node.title %></td>
        <td class="item_price"><%= number_to_currency(node.price*rel[:quantity])%></td>
      </tr>
  <% end %>
  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"> <%= number_to_currency(@cart.sum_price)%></td>
  </tr>
</table>
<div>
  <%= button_to "Checkout" , new_order_path, method: :get %>
  <%= button_to 'Empty cart', @cart, method: :delete,
              data: { confirm: 'Are you sure?' } %>
</div>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/create.js.erb
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%=j render(@cart) %>");

$('.rightside').html("<%=j render('recommendation/recommendation') %>");

$('#current_item').css({'background-color':'yellow'}).
  animate({'background-color':'white'}, 1000);

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.uuid %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<%= render @cart%>

<%= link_to 'Back', carts_path %>